/**
 * default-rules.js
 * Базовый словарь правил автоопределения категорий при парсинге выписок.
 * Подключается перед statement-parser.js и app.js.
 */

const DEFAULT_CATEGORY_RULES = [
  // =========================================================
  // 1. ПРОДУКТЫ И СУПЕРМАРКЕТЫ (включая доставку)
  // =========================================================
  { pattern: "perek", category: "Продукты" },
  { pattern: "перекресток", category: "Продукты" },
  { pattern: "pyaterochka", category: "Продукты" },
  { pattern: "пятерочка", category: "Продукты" },
  { pattern: "okey", category: "Продукты" },
  { pattern: "окей", category: "Продукты" },
  { pattern: "lenta", category: "Продукты" },
  { pattern: "лента", category: "Продукты" },
  { pattern: "magnit", category: "Продукты" },
  { pattern: "магнит", category: "Продукты" },
  { pattern: "krasnoe", category: "Продукты" },
  { pattern: "красное и белое", category: "Продукты" },
  { pattern: "fixprice", category: "Продукты" },
  { pattern: "фикс прайс", category: "Продукты" },
  { pattern: "dixy", category: "Продукты" },
  { pattern: "дикси", category: "Продукты" },
  { pattern: "vkusvill", category: "Продукты" },
  { pattern: "вкусвилл", category: "Продукты" },
  { pattern: "избёнка", category: "Продукты" },
  { pattern: "samokat", category: "Продукты" },
  { pattern: "самокат", category: "Продукты" },
  { pattern: "умный ритейл", category: "Продукты" },
  { pattern: "lavka", category: "Продукты" },
  { pattern: "яндекс лавка", category: "Продукты" },
  { pattern: "kuper", category: "Продукты" },
  { pattern: "купер", category: "Продукты" },
  { pattern: "sbermarket", category: "Продукты" },
  { pattern: "сбермаркет", category: "Продукты" },
  { pattern: "auchan", category: "Продукты" },
  { pattern: "ашан", category: "Продукты" },
  { pattern: "atack", category: "Продукты" },
  { pattern: "атак", category: "Продукты" },
  { pattern: "metro", category: "Продукты" },
  { pattern: "метро c&c", category: "Продукты" },
  { pattern: "chizhik", category: "Продукты" },
  { pattern: "чижик", category: "Продукты" },
  { pattern: "spar", category: "Продукты" },
  { pattern: "спар", category: "Продукты" },
  { pattern: "azbuka", category: "Продукты" },
  { pattern: "азбука вкуса", category: "Продукты" },
  { pattern: "верный", category: "Продукты" },
  { pattern: "ярче", category: "Продукты" },
  { pattern: "пекарня", category: "Продукты" },

  // =========================================================
  // 2. КАФЕ И РЕСТОРАНЫ (общепит и готовая еда)
  // =========================================================
  { pattern: "vlavashe", category: "Кафе и рестораны" },
  { pattern: "rostics", category: "Кафе и рестораны" },
  { pattern: "ростикс", category: "Кафе и рестораны" },
  { pattern: "kfc", category: "Кафе и рестораны" },
  { pattern: "kimchi to go", category: "Кафе и рестораны" },
  { pattern: "mu mu burgers", category: "Кафе и рестораны" },
  { pattern: "bros burritos", category: "Кафе и рестораны" },
  { pattern: "dostaevsky", category: "Кафе и рестораны" },
  { pattern: "nesselbek", category: "Кафе и рестораны" },
  { pattern: "dom lunda", category: "Кафе и рестораны" },
  { pattern: "krem", category: "Кафе и рестораны" },
  { pattern: "kozhura", category: "Кафе и рестораны" },
  { pattern: "bulochnaya", category: "Кафе и рестораны" },
  { pattern: "булочная", category: "Кафе и рестораны" },
  { pattern: "restoran", category: "Кафе и рестораны" },
  { pattern: "varochnaya", category: "Кафе и рестораны" },
  { pattern: "pizza", category: "Кафе и рестораны" },
  { pattern: "burger", category: "Кафе и рестораны" },
  { pattern: "tokyo city", category: "Кафе и рестораны" },
  { pattern: "1st food factory", category: "Кафе и рестораны" },
  { pattern: "vkusno", category: "Кафе и рестораны" },
  { pattern: "вкусно и точка", category: "Кафе и рестораны" },
  { pattern: "dodo", category: "Кафе и рестораны" },
  { pattern: "додо", category: "Кафе и рестораны" },
  { pattern: "burger king", category: "Кафе и рестораны" },
  { pattern: "бургер кинг", category: "Кафе и рестораны" },
  { pattern: "teremok", category: "Кафе и рестораны" },
  { pattern: "теремок", category: "Кафе и рестораны" },
  { pattern: "shokoladnitsa", category: "Кафе и рестораны" },
  { pattern: "шоколадница", category: "Кафе и рестораны" },
  { pattern: "stars coffee", category: "Кафе и рестораны" },
  { pattern: "starbucks", category: "Кафе и рестораны" },
  { pattern: "cofix", category: "Кафе и рестораны" },
  { pattern: "кофикс", category: "Кафе и рестораны" },
  { pattern: "one price", category: "Кафе и рестораны" },
  { pattern: "дринкит", category: "Кафе и рестораны" },
  { pattern: "drinkit", category: "Кафе и рестораны" },
  { pattern: "eda.yandex", category: "Кафе и рестораны" },
  { pattern: "яндекс еда", category: "Кафе и рестораны" },
  { pattern: "delivery club", category: "Кафе и рестораны" },
  { pattern: "деливери", category: "Кафе и рестораны" },
  { pattern: "кулинария", category: "Кафе и рестораны" },
  { pattern: "столовая", category: "Кафе и рестораны" },
  { pattern: "суши", category: "Кафе и рестораны" },
  { pattern: "sushi", category: "Кафе и рестораны" },
  { pattern: "шаурма", category: "Кафе и рестораны" },
  { pattern: "шаверма", category: "Кафе и рестораны" },
  { pattern: "кофейня", category: "Кафе и рестораны" },
  { pattern: "бар", category: "Кафе и рестораны" },
  { pattern: "паб", category: "Кафе и рестораны" },
  { pattern: "pub", category: "Кафе и рестораны" },

  // =========================================================
  // 3. МАРКЕТПЛЕЙСЫ
  // =========================================================
  { pattern: "wb", category: "Маркетплейсы" },
  { pattern: "wildberries", category: "Маркетплейсы" },
  { pattern: "ozon", category: "Маркетплейсы" },
  { pattern: "озон", category: "Маркетплейсы" },
  { pattern: "market.yandex", category: "Маркетплейсы" },
  { pattern: "яндекс маркет", category: "Маркетплейсы" },
  { pattern: "yandex market", category: "Маркетплейсы" },
  { pattern: "megamarket", category: "Маркетплейсы" },
  { pattern: "мегамаркет", category: "Маркетплейсы" },
  { pattern: "sbermegamarket", category: "Маркетплейсы" },
  { pattern: "aliexpress", category: "Маркетплейсы" },
  { pattern: "алиэкспресс", category: "Маркетплейсы" },
  { pattern: "avito", category: "Маркетплейсы" },
  { pattern: "авито", category: "Маркетплейсы" },
  { pattern: "kazanexpress", category: "Маркетплейсы" },
  { pattern: "магнит маркет", category: "Маркетплейсы" },

  // =========================================================
  // 4. ТРАНСПОРТ, АЗС И ПОЕЗДКИ
  // =========================================================
  { pattern: "rzd", category: "Транспорт" },
  { pattern: "ржд", category: "Транспорт" },
  { pattern: "szppk", category: "Транспорт" },
  { pattern: "сзппк", category: "Транспорт" },
  { pattern: "transkom", category: "Транспорт" },
  { pattern: "транском", category: "Транспорт" },
  { pattern: "taxi", category: "Транспорт" },
  { pattern: "такси", category: "Транспорт" },
  { pattern: "yandex.go", category: "Транспорт" },
  { pattern: "яндекс го", category: "Транспорт" },
  { pattern: "citydrive", category: "Транспорт" },
  { pattern: "ситидрайв", category: "Транспорт" },
  { pattern: "delimobil", category: "Транспорт" },
  { pattern: "делимобиль", category: "Транспорт" },
  { pattern: "каршеринг", category: "Транспорт" },
  { pattern: "drive", category: "Транспорт" },
  { pattern: "яндекс драйв", category: "Транспорт" },
  { pattern: "лукойл", category: "Транспорт" },
  { pattern: "lukoil", category: "Транспорт" },
  { pattern: "газпромнефть", category: "Транспорт" },
  { pattern: "gpn", category: "Транспорт" },
  { pattern: "роснефть", category: "Транспорт" },
  { pattern: "rosneft", category: "Транспорт" },
  { pattern: "татнефть", category: "Транспорт" },
  { pattern: "tatneft", category: "Транспорт" },
  { pattern: "тебойл", category: "Транспорт" },
  { pattern: "teboil", category: "Транспорт" },
  { pattern: "азс", category: "Транспорт" },
  { pattern: "бензин", category: "Транспорт" },
  { pattern: "заправка", category: "Транспорт" },
  { pattern: "московский метрополитен", category: "Транспорт" },
  { pattern: "мосметро", category: "Транспорт" },
  { pattern: "петербургский метрополитен", category: "Транспорт" },
  { pattern: "метро спб", category: "Транспорт" },
  { pattern: "тройка", category: "Транспорт" },
  { pattern: "подорожник", category: "Транспорт" },
  { pattern: "парковк", category: "Транспорт" },
  { pattern: "parking", category: "Транспорт" },
  { pattern: "паркинг", category: "Транспорт" },
  { pattern: "моспаркинг", category: "Транспорт" },
  { pattern: "aeroflot", category: "Транспорт" },
  { pattern: "аэрофлот", category: "Транспорт" },
  { pattern: "pobeda", category: "Транспорт" },
  { pattern: "победа", category: "Транспорт" },
  { pattern: "s7", category: "Транспорт" },
  { pattern: "авиабилеты", category: "Транспорт" },
  { pattern: "mezhdunarodnaya", category: "Транспорт" },
  { pattern: "baltiyskaya", category: "Транспорт" },
  { pattern: "pionerskaya", category: "Транспорт" },
  { pattern: "tekhnol", category: "Транспорт" },
  { pattern: "pl. lenina", category: "Транспорт" },

  // =========================================================
  // 5. ЖИЛЬЕ, СВЯЗЬ И РЕМОНТ
  // =========================================================
  { pattern: "жкх", category: "Жилье" },
  { pattern: "квартплат", category: "Жилье" },
  { pattern: "еирц", category: "Жилье" },
  { pattern: "мособлеирц", category: "Жилье" },
  { pattern: "жкт", category: "Жилье" },
  { pattern: "коммунал", category: "Жилье" },
  { pattern: "мосэнергосбыт", category: "Жилье" },
  { pattern: "петроэлектросбыт", category: "Жилье" },
  { pattern: "энергосбыт", category: "Жилье" },
  { pattern: "водоканал", category: "Жилье" },
  { pattern: "ростелеком", category: "Жилье" },
  { pattern: "rostelecom", category: "Жилье" },
  { pattern: "дом.ру", category: "Жилье" },
  { pattern: "dom.ru", category: "Жилье" },
  { pattern: "мтс", category: "Жилье" },
  { pattern: "mts", category: "Жилье" },
  { pattern: "билайн", category: "Жилье" },
  { pattern: "beeline", category: "Жилье" },
  { pattern: "мегафон", category: "Жилье" },
  { pattern: "megafon", category: "Жилье" },
  { pattern: "tele2", category: "Жилье" },
  { pattern: "t2", category: "Жилье" },
  { pattern: "yota", category: "Жилье" },
  { pattern: "йота", category: "Жилье" },
  { pattern: "leroy", category: "Жилье" },
  { pattern: "леруа", category: "Жилье" },
  { pattern: "лемана", category: "Жилье" },
  { pattern: "lemana", category: "Жилье" },
  { pattern: "петрович", category: "Жилье" },
  { pattern: "petrovich", category: "Жилье" },
  { pattern: "максидом", category: "Жилье" },
  { pattern: "всеинструменты", category: "Жилье" },
  { pattern: "vseinstrumenti", category: "Жилье" },

  // =========================================================
  // 6. ОДЕЖДА И ОБУВЬ
  // =========================================================
  { pattern: "zara", category: "Одежда" },
  { pattern: "befree", category: "Одежда" },
  { pattern: "lime", category: "Одежда" },
  { pattern: "лайм", category: "Одежда" },
  { pattern: "zarina", category: "Одежда" },
  { pattern: "зарина", category: "Одежда" },
  { pattern: "gloria", category: "Одежда" },
  { pattern: "глория", category: "Одежда" },
  { pattern: "ostin", category: "Одежда" },
  { pattern: "остин", category: "Одежда" },
  { pattern: "rendez", category: "Одежда" },
  { pattern: "рандеву", category: "Одежда" },
  { pattern: "sportmaster", category: "Одежда" },
  { pattern: "спортмастер", category: "Одежда" },
  { pattern: "ecco", category: "Одежда" },
  { pattern: "экко", category: "Одежда" },
  { pattern: "kari", category: "Одежда" },
  { pattern: "кари", category: "Одежда" },
  { pattern: "lamoda", category: "Одежда" },
  { pattern: "ламода", category: "Одежда" },
  { pattern: "colins", category: "Одежда" },
  { pattern: "колинс", category: "Одежда" },
  { pattern: "calzedonia", category: "Одежда" },
  { pattern: "intimissimi", category: "Одежда" },
  { pattern: "love republic", category: "Одежда" },
  { pattern: "sinsay", category: "Одежда" },
  { pattern: "reserved", category: "Одежда" },
  { pattern: "familia", category: "Одежда" },
  { pattern: "фамилия", category: "Одежда" },
  { pattern: "funday", category: "Одежда" },
  { pattern: "фандей", category: "Одежда" },
  { pattern: "henderson", category: "Одежда" },
  { pattern: "хендерсон", category: "Одежда" },
  { pattern: "снежная королева", category: "Одежда" },
  { pattern: "snowqueen", category: "Одежда" },
  { pattern: "tezenis", category: "Одежда" },
  { pattern: "incanto", category: "Одежда" },
  { pattern: "finn flare", category: "Одежда" },
  { pattern: "фин флэр", category: "Одежда" },
  { pattern: "geox", category: "Одежда" },
  { pattern: "street beat", category: "Одежда" },
  { pattern: "стрит бит", category: "Одежда" },
  { pattern: "шоурум", category: "Одежда" },
  { pattern: "ателье", category: "Одежда" },
  { pattern: "трикотаж", category: "Одежда" },
  { pattern: "одежда", category: "Одежда" },
  { pattern: "обувь", category: "Одежда" },

  // =========================================================
  // 7. ЗДОРОВЬЕ И МЕДИЦИНА
  // =========================================================
  { pattern: "apteka", category: "Здоровье" },
  { pattern: "аптека", category: "Здоровье" },
  { pattern: "rigla", category: "Здоровье" },
  { pattern: "ригла", category: "Здоровье" },
  { pattern: "eapteka", category: "Здоровье" },
  { pattern: "еаптека", category: "Здоровье" },
  { pattern: "gorzdrav", category: "Здоровье" },
  { pattern: "горздрав", category: "Здоровье" },
  { pattern: "vita", category: "Здоровье" },
  { pattern: "вита", category: "Здоровье" },
  { pattern: "планета здоровья", category: "Здоровье" },
  { pattern: "столички", category: "Здоровье" },
  { pattern: "ozerki", category: "Здоровье" },
  { pattern: "озерки", category: "Здоровье" },
  { pattern: "невис", category: "Здоровье" },
  { pattern: "helix", category: "Здоровье" },
  { pattern: "хеликс", category: "Здоровье" },
  { pattern: "invitro", category: "Здоровье" },
  { pattern: "инвитро", category: "Здоровье" },
  { pattern: "gemotest", category: "Здоровье" },
  { pattern: "гемотест", category: "Здоровье" },
  { pattern: "клиника", category: "Здоровье" },
  { pattern: "clinic", category: "Здоровье" },
  { pattern: "стоматолог", category: "Здоровье" },
  { pattern: "stomatolog", category: "Здоровье" },
  { pattern: "стоматология", category: "Здоровье" },
  { pattern: "dental", category: "Здоровье" },
  { pattern: "медси", category: "Здоровье" },
  { pattern: "medsi", category: "Здоровье" },
  { pattern: "скандинавия", category: "Здоровье" },
  { pattern: "евромед", category: "Здоровье" },
  { pattern: "буду", category: "Здоровье" },
  { pattern: "budu", category: "Здоровье" },
  { pattern: "сберздоровье", category: "Здоровье" },
  { pattern: "линзмастер", category: "Здоровье" },
  { pattern: "линзы", category: "Здоровье" },
  { pattern: "оптика", category: "Здоровье" },
  { pattern: "анализы", category: "Здоровье" },
  { pattern: "лаборатория", category: "Здоровье" },
  { pattern: "мрт", category: "Здоровье" },
  { pattern: "рентген", category: "Здоровье" },
  { pattern: "медицин", category: "Здоровье" },
  { pattern: "фитнес", category: "Развлечения" },
  { pattern: "fitness", category: "Развлечения" },
  { pattern: "world class", category: "Развлечения" },
  { pattern: "ddx", category: "Развлечения" },
  { pattern: "бассейн", category: "Развлечения" },

  // =========================================================
  // 8. РАЗВЛЕЧЕНИЯ И ЦИФРОВЫЕ ПОДПИСКИ
  // =========================================================
  { pattern: "muzej", category: "Развлечения" },
  { pattern: "музей", category: "Развлечения" },
  { pattern: "homlins", category: "Развлечения" },
  { pattern: "afisha", category: "Развлечения" },
  { pattern: "афиша", category: "Развлечения" },
  { pattern: "teatr", category: "Развлечения" },
  { pattern: "театр", category: "Развлечения" },
  { pattern: "shtiglitsa", category: "Развлечения" },
  { pattern: "кино", category: "Развлечения" },
  { pattern: "cinema", category: "Развлечения" },
  { pattern: "kinoteatr", category: "Развлечения" },
  { pattern: "синема парк", category: "Развлечения" },
  { pattern: "формула кино", category: "Развлечения" },
  { pattern: "каро", category: "Развлечения" },
  { pattern: "киномакс", category: "Развлечения" },
  { pattern: "мираж", category: "Развлечения" },
  { pattern: "яндекс плюс", category: "Развлечения" },
  { pattern: "plus.yandex", category: "Развлечения" },
  { pattern: "yandex plus", category: "Развлечения" },
  { pattern: "кинопоиск", category: "Развлечения" },
  { pattern: "kinopoisk", category: "Развлечения" },
  { pattern: "иви", category: "Развлечения" },
  { pattern: "ivi", category: "Развлечения" },
  { pattern: "okko", category: "Развлечения" },
  { pattern: "окко", category: "Развлечения" },
  { pattern: "premier", category: "Развлечения" },
  { pattern: "kion", category: "Развлечения" },
  { pattern: "kassir", category: "Развлечения" },
  { pattern: "кассир", category: "Развлечения" },
  { pattern: "ticketland", category: "Развлечения" },
  { pattern: "тикетлэнд", category: "Развлечения" },
  { pattern: "steam", category: "Развлечения" },
  { pattern: "playstation", category: "Развлечения" },
  { pattern: "ps store", category: "Развлечения" },
  { pattern: "vk play", category: "Развлечения" },

  // =========================================================
  // 9. ДОХОДЫ (Зарплата, Кэшбек, Возвраты)
  // =========================================================
  { pattern: "заработная плата", category: "Зарплата" },
  { pattern: "salary", category: "Зарплата" },
  { pattern: "аванс", category: "Зарплата" },
  { pattern: "отпускные", category: "Зарплата" },
  { pattern: "премия", category: "Зарплата" },
  { pattern: "бонус", category: "Зарплата" },
  { pattern: "материальная помощь", category: "Зарплата" },
  { pattern: "расчет при увольнении", category: "Зарплата" },
  { pattern: "компенсация", category: "Зарплата" },
  { pattern: "выплата зп", category: "Зарплата" },
  { pattern: "выплата процентов", category: "Зарплата" },
  { pattern: "проценты по вкладу", category: "Зарплата" },
  { pattern: "проценты на остаток", category: "Зарплата" },
  { pattern: "дивиденды", category: "Зарплата" },
  { pattern: "кешбек", category: "Кэшбек" },
  { pattern: "баллами Плюса", category: "Кэшбек" },
  { pattern: "возврат", category: "Возврат" }
];

if (typeof window !== 'undefined') {
  window.DEFAULT_CATEGORY_RULES = DEFAULT_CATEGORY_RULES;
}
