/**
 * default-rules.js
 * Базовый словарь правил автоопределения категорий.
 * Все слова автоматически нормализуются: совпадения находят и русский, и транслит.
 */

const DEFAULT_CATEGORY_RULES = [
  // 1. ПРОДУКТЫ И СУПЕРМАРКЕТЫ
  { pattern: "перекресток", category: "Продукты" },
  { pattern: "perek", category: "Продукты" },
  { pattern: "пятерочка", category: "Продукты" },
  { pattern: "окей", category: "Продукты" },
  { pattern: "лента", category: "Продукты" },
  { pattern: "магнит", category: "Продукты" },
  { pattern: "красное и белое", category: "Продукты" },
  { pattern: "фикс прайс", category: "Продукты" },
  { pattern: "дикси", category: "Продукты" },
  { pattern: "вкусвилл", category: "Продукты" },
  { pattern: "избенка", category: "Продукты" },
  { pattern: "самокат", category: "Продукты" },
  { pattern: "умный ритейл", category: "Продукты" },
  { pattern: "яндекс лавка", category: "Продукты" },
  { pattern: "купер", category: "Продукты" },
  { pattern: "сбермаркет", category: "Продукты" },
  { pattern: "ашан", category: "Продукты" },
  { pattern: "атак", category: "Продукты" },
  { pattern: "метро", category: "Продукты" },
  { pattern: "чижик", category: "Продукты" },
  { pattern: "спар", category: "Продукты" },
  { pattern: "азбука вкуса", category: "Продукты" },
  { pattern: "верный", category: "Продукты" },
  { pattern: "пекарня", category: "Продукты" },

  // 2. КАФЕ И РЕСТОРАНЫ
  { pattern: "vlavashe", category: "Кафе и рестораны" },
  { pattern: "ростикс", category: "Кафе и рестораны" },
  { pattern: "kfc", category: "Кафе и рестораны" },
  { pattern: "kimchi to go", category: "Кафе и рестораны" },
  { pattern: "му му", category: "Кафе и рестораны" },
  { pattern: "bros burritos", category: "Кафе и рестораны" },
  { pattern: "достаевский", category: "Кафе и рестораны" },
  { pattern: "нессельбек", category: "Кафе и рестораны" },
  { pattern: "dom lunda", category: "Кафе и рестораны" },
  { pattern: "крем", category: "Кафе и рестораны" },
  { pattern: "кожура", category: "Кафе и рестораны" },
  { pattern: "булочная", category: "Кафе и рестораны" },
  { pattern: "ресторан", category: "Кафе и рестораны" },
  { pattern: "варочная", category: "Кафе и рестораны" },
  { pattern: "пицца", category: "Кафе и рестораны" },
  { pattern: "бургер", category: "Кафе и рестораны" },
  { pattern: "токио сити", category: "Кафе и рестораны" },
  { pattern: "1st food factory", category: "Кафе и рестораны" },
  { pattern: "вкусно и точка", category: "Кафе и рестораны" },
  { pattern: "додо", category: "Кафе и рестораны" },
  { pattern: "бургер кинг", category: "Кафе и рестораны" },
  { pattern: "теремок", category: "Кафе и рестораны" },
  { pattern: "шоколадница", category: "Кафе и рестораны" },
  { pattern: "старбакс", category: "Кафе и рестораны" },
  { pattern: "stars coffee", category: "Кафе и рестораны" },
  { pattern: "кофикс", category: "Кафе и рестораны" },
  { pattern: "one price", category: "Кафе и рестораны" },
  { pattern: "дринкит", category: "Кафе и рестораны" },
  { pattern: "яндекс еда", category: "Кафе и рестораны" },
  { pattern: "деливери", category: "Кафе и рестораны" },
  { pattern: "кулинария", category: "Кафе и рестораны" },
  { pattern: "столовая", category: "Кафе и рестораны" },
  { pattern: "суши", category: "Кафе и рестораны" },
  { pattern: "шаурма", category: "Кафе и рестораны" },
  { pattern: "шаверма", category: "Кафе и рестораны" },
  { pattern: "кофейня", category: "Кафе и рестораны" },
  { pattern: "кофе", category: "Кафе и рестораны" },
  { pattern: "бар", category: "Кафе и рестораны" },
  { pattern: "паб", category: "Кафе и рестораны" },

  // 3. МАРКЕТПЛЕЙСЫ
  { pattern: "wb", category: "Маркетплейсы" },
  { pattern: "вайлдберриз", category: "Маркетплейсы" },
  { pattern: "озон", category: "Маркетплейсы" },
  { pattern: "яндекс маркет", category: "Маркетплейсы" },
  { pattern: "мегамаркет", category: "Маркетплейсы" },
  { pattern: "сбермегамаркет", category: "Маркетплейсы" },
  { pattern: "алиэкспресс", category: "Маркетплейсы" },
  { pattern: "авито", category: "Маркетплейсы" },
  { pattern: "казаньэкспресс", category: "Маркетплейсы" },
  { pattern: "магнит маркет", category: "Маркетплейсы" },

  // 4. ТРАНСПОРТ, АЗС И ПОЕЗДКИ
  { pattern: "ржд", category: "Транспорт" },
  { pattern: "сзппк", category: "Транспорт" },
  { pattern: "транском", category: "Транспорт" },
  { pattern: "такси", category: "Транспорт" },
  { pattern: "яндекс го", category: "Транспорт" },
  { pattern: "ситидрайв", category: "Транспорт" },
  { pattern: "делимобиль", category: "Транспорт" },
  { pattern: "каршеринг", category: "Транспорт" },
  { pattern: "яндекс драйв", category: "Транспорт" },
  { pattern: "лукойл", category: "Транспорт" },
  { pattern: "газпромнефть", category: "Транспорт" },
  { pattern: "роснефть", category: "Транспорт" },
  { pattern: "татнефть", category: "Транспорт" },
  { pattern: "тебойл", category: "Транспорт" },
  { pattern: "азс", category: "Транспорт" },
  { pattern: "бензин", category: "Транспорт" },
  { pattern: "заправка", category: "Транспорт" },
  { pattern: "метрополитен", category: "Транспорт" },
  { pattern: "мосметро", category: "Транспорт" },
  { pattern: "метро спб", category: "Транспорт" },
  { pattern: "тройка", category: "Транспорт" },
  { pattern: "подорожник", category: "Транспорт" },
  { pattern: "парковка", category: "Транспорт" },
  { pattern: "паркинг", category: "Транспорт" },
  { pattern: "моспаркинг", category: "Транспорт" },
  { pattern: "аэрофлот", category: "Транспорт" },
  { pattern: "победа", category: "Транспорт" },
  { pattern: "s7", category: "Транспорт" },
  { pattern: "авиабилеты", category: "Транспорт" },
  { pattern: "международная", category: "Транспорт" },
  { pattern: "балтийская", category: "Транспорт" },
  { pattern: "пионерская", category: "Транспорт" },
  { pattern: "технологический", category: "Транспорт" },
  { pattern: "площадь ленина", category: "Транспорт" },

  // 5. ЖИЛЬЕ, СВЯЗЬ И РЕМОНТ
  { pattern: "жкх", category: "Жилье" },
  { pattern: "квартплата", category: "Жилье" },
  { pattern: "еирц", category: "Жилье" },
  { pattern: "мособлеирц", category: "Жилье" },
  { pattern: "жкт", category: "Жилье" },
  { pattern: "коммунал", category: "Жилье" },
  { pattern: "мосэнергосбыт", category: "Жилье" },
  { pattern: "петроэлектросбыт", category: "Жилье" },
  { pattern: "энергосбыт", category: "Жилье" },
  { pattern: "водоканал", category: "Жилье" },
  { pattern: "ростелеком", category: "Жилье" },
  { pattern: "дом ру", category: "Жилье" },
  { pattern: "мтс", category: "Жилье" },
  { pattern: "билайн", category: "Жилье" },
  { pattern: "мегафон", category: "Жилье" },
  { pattern: "tele2", category: "Жилье" },
  { pattern: "t2", category: "Жилье" },
  { pattern: "йота", category: "Жилье" },
  { pattern: "леруа", category: "Жилье" },
  { pattern: "лемана", category: "Жилье" },
  { pattern: "петрович", category: "Жилье" },
  { pattern: "максидом", category: "Жилье" },
  { pattern: "всеинструменты", category: "Жилье" },

  // 6. ОДЕЖДА И ОБУВЬ
  { pattern: "zara", category: "Одежда" },
  { pattern: "befree", category: "Одежда" },
  { pattern: "лайм", category: "Одежда" },
  { pattern: "зарина", category: "Одежда" },
  { pattern: "глория", category: "Одежда" },
  { pattern: "остин", category: "Одежда" },
  { pattern: "рандеву", category: "Одежда" },
  { pattern: "спортмастер", category: "Одежда" },
  { pattern: "экко", category: "Одежда" },
  { pattern: "кари", category: "Одежда" },
  { pattern: "ламода", category: "Одежда" },
  { pattern: "колинс", category: "Одежда" },
  { pattern: "кальцедония", category: "Одежда" },
  { pattern: "интимиссими", category: "Одежда" },
  { pattern: "love republic", category: "Одежда" },
  { pattern: "sinsay", category: "Одежда" },
  { pattern: "reserved", category: "Одежда" },
  { pattern: "фамилия", category: "Одежда" },
  { pattern: "фандей", category: "Одежда" },
  { pattern: "хендерсон", category: "Одежда" },
  { pattern: "снежная королева", category: "Одежда" },
  { pattern: "tezenis", category: "Одежда" },
  { pattern: "incanto", category: "Одежда" },
  { pattern: "фин флэр", category: "Одежда" },
  { pattern: "джеокс", category: "Одежда" },
  { pattern: "стрит бит", category: "Одежда" },
  { pattern: "шоурум", category: "Одежда" },
  { pattern: "ателье", category: "Одежда" },
  { pattern: "трикотаж", category: "Одежда" },
  { pattern: "одежда", category: "Одежда" },
  { pattern: "обувь", category: "Одежда" },

  // 7. ЗДОРОВЬЕ И МЕДИЦИНА
  { pattern: "аптека", category: "Здоровье" },
  { pattern: "ригла", category: "Здоровье" },
  { pattern: "еаптека", category: "Здоровье" },
  { pattern: "горздрав", category: "Здоровье" },
  { pattern: "вита", category: "Здоровье" },
  { pattern: "планета здоровья", category: "Здоровье" },
  { pattern: "столички", category: "Здоровье" },
  { pattern: "озерки", category: "Здоровье" },
  { pattern: "невис", category: "Здоровье" },
  { pattern: "хеликс", category: "Здоровье" },
  { pattern: "инвитро", category: "Здоровье" },
  { pattern: "гемотест", category: "Здоровье" },
  { pattern: "клиника", category: "Здоровье" },
  { pattern: "стоматолог", category: "Здоровье" },
  { pattern: "стоматология", category: "Здоровье" },
  { pattern: "медси", category: "Здоровье" },
  { pattern: "скандинавия", category: "Здоровье" },
  { pattern: "евромед", category: "Здоровье" },
  { pattern: "сберздоровье", category: "Здоровье" },
  { pattern: "айкрафт", category: "Здоровье" },
  { pattern: "линзмастер", category: "Здоровье" },
  { pattern: "линзы", category: "Здоровье" },
  { pattern: "оптика", category: "Здоровье" },
  { pattern: "анализы", category: "Здоровье" },
  { pattern: "лаборатория", category: "Здоровье" },
  { pattern: "мрт", category: "Здоровье" },
  { pattern: "рентген", category: "Здоровье" },
  { pattern: "медицин", category: "Здоровье" },
  { pattern: "фитнес", category: "Здоровье" },
  { pattern: "world class", category: "Здоровье" },
  { pattern: "ddx", category: "Здоровье" },
  { pattern: "бассейн", category: "Здоровье" },

  // 8. РАЗВЛЕЧЕНИЯ И ПОДПИСКИ
  { pattern: "музей", category: "Развлечения" },
  { pattern: "хомлины", category: "Развлечения" },
  { pattern: "афиша", category: "Развлечения" },
  { pattern: "театр", category: "Развлечения" },
  { pattern: "кино", category: "Развлечения" },
  { pattern: "кинотеатр", category: "Развлечения" },
  { pattern: "синема парк", category: "Развлечения" },
  { pattern: "формула кино", category: "Развлечения" },
  { pattern: "киномакс", category: "Развлечения" },
  { pattern: "мираж", category: "Развлечения" },
  { pattern: "яндекс плюс", category: "Развлечения" },
  { pattern: "кинопоиск", category: "Развлечения" },
  { pattern: "иви", category: "Развлечения" },
  { pattern: "окко", category: "Развлечения" },
  { pattern: "премьер", category: "Развлечения" },
  { pattern: "кион", category: "Развлечения" },
  { pattern: "кассир", category: "Развлечения" },
  { pattern: "тикетлэнд", category: "Развлечения" },
  { pattern: "steam", category: "Развлечения" },
  { pattern: "playstation", category: "Развлечения" },
  { pattern: "vk play", category: "Развлечения" },

  // 9. ДОХОДЫ
  { pattern: "заработная плата", category: "Зарплата" },
  { pattern: "зарплата", category: "Зарплата" },
  { pattern: "аванс", category: "Зарплата" },
  { pattern: "отпускные", category: "Зарплата" },
  { pattern: "премия", category: "Зарплата" },
  { pattern: "материальная помощь", category: "Зарплата" },
  { pattern: "расчет при увольнении", category: "Зарплата" },
  { pattern: "компенсация", category: "Зарплата" },
  { pattern: "дивиденды", category: "Зарплата" },
  { pattern: "кешбек", category: "Кэшбек" },
  { pattern: "баллами плюса", category: "Кэшбек" },
  { pattern: "возврат", category: "Возврат" }
];

if (typeof window !== 'undefined') {
  window.DEFAULT_CATEGORY_RULES = DEFAULT_CATEGORY_RULES;
}
